[project]
name = "cicd"
version = "0.1.0"
description = ""
authors = [{ name = "Adam Connolly", email = "45522351+aconn1994@users.noreply.github.com" }]
requires-python = ">=3.13"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.9.4,<0.10.0",
    "pytest>=8.3.4,<9.0.0",
    "coverage>=7.8.0",
    "mypy==1.15.0",
]

[tool.hatch.build.targets.sdist]
include = ["cst_cicd"]

[tool.hatch.build.targets.wheel]
include = ["cst_cicd"]

[tool.ruff.lint]
select = [
    "F401", # unused imports
    "F841", # unused variables
    "I",    # isort
    "INP",  # flake8-no-pep420 == __init__ scanner
]
ignore = [
    "B904",     # use 'raise ... from err'
    "E111",     # indentation-with-invalid-multiple clashes with formatter
    "E114",     # indentation-with-invalid-multiple-comment clashes with formatter
    "E117",     # over-indented clashes with formatter
    "G004",     # logging statements use f-string
    "N817",     # CamelCase imported as acronym
    "N818",     # Exception name should be named with an Error suffix
    "PD901",    # Avoid using generic variables name 'df' for DataFrames
    "PLR2004",  # No magic values
    "W191",     # tab-indentation will conflict with formatter
]
unfixable = [
    "ERA" # do not autoremove commented out code
]

[tool.ruff.lint.pylint]
max-args = 12

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
docstring-code-format = true
exclude = []

[tool.mypy]
python_version = "3.13"
disallow_untyped_defs = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
strict_optional = false
exclude = '/tests/'

[tool.pytest.ini_options]
markers = ["excluded: test to not run with coverage"]

[tool.coverage.run]
source = ["cst_cicd"]

[tool.coverage.report]
fail_under = 90.00
precision = 2
ignore_errors = true
skip_empty = true
omit = [
    "*/tests/*",
]
exclude_lines = [
    "pragma: no cover"
]
