services:
  cst-base:
    container_name: cst-base-container
    image: cst-base:latest
    platform: linux/amd64
    build:
      dockerfile: local_env/images/base_image/Dockerfile
      context: .
    privileged: true
    user: root
    working_dir: /root/cloud-server-tool
    volumes:
      - .:/root/cloud-server-tool:rw,z
    entrypoint: /bin/bash

  cst-debug:
    container_name: cst-debug-container
    image: cst_debug:latest
    platform: linux/amd64
    build:
      dockerfile: local_env/images/debug_image/Dockerfile
      context: .
    privileged: true
    user: root
    working_dir: /root/cloud-server-tool
    volumes:
      - .:/root/cloud-server-tool:rw,z
    ports:
      - "2223:22"
    depends_on:
      - cst-base

  arma-three-server:
    container_name: arma-three-server-container
    image: game_server:latest
    platform: linux/amd64
    build:
      dockerfile: lib/python/cst/cst_docker/Dockerfile
      context: .
      args:
        IMAGE: ubuntu
        PORTS: 2302/udp 2303/udp 2304/udp 2305/udp 2306/udp
        INSTALL_DEPENDENCIES: lib32stdc++6 lib32gcc-s1
        STEAM_USERNAME_ARG: BigDaddyDong69
        STEAM_PASSWORD_ARG: 77hMQupPfgeVRd8EkUNR
    privileged: true
    user: gameuser
    working_dir: /home/gameuser
    volumes:
      - ./lib/python/cst/cst_game:/home/gameuser/cst_game:rw,z
    entrypoint: /bin/bash
    tty: true