#!/usr/bin/python3

import os
import SteamClient.SteamCMDClient as SCC
import GameConfigClient.GameConfigClient as GCC


def main():

    # Environment Variables (DockerFile)
    STEAMCMD_DIR: str = os.path.join(os.getcwd(), os.environ['DIR_STEAMCMD'])
    LOCAL_GAME_ID: str = os.environ['DIR_LOCAL_GAME']
    LOCAL_GAME_DIR: str = os.path.join(STEAMCMD_DIR, LOCAL_GAME_ID)
    LOCAL_MOD_DIR: str = os.path.join(LOCAL_GAME_DIR, os.environ['DIR_LOCAL_MOD'])
    LOCAL_KEYS_DIR: str = os.path.join(LOCAL_GAME_DIR, os.environ['DIR_KEYS_DIR'])
    STEAM_USERNAME: str = os.environ['STEAM_USERNAME']
    STEAM_PASSWORD: str = os.environ['STEAM_PASSWORD']
    GAME_SERVER_ID: str = os.environ['GAME_SERVER_ID']
    GAME_WORKSHOP_ID: str = os.environ['GAME_WORKSHOP_ID']
    STEAM_DOWNLOAD_DIR: str = os.path.join(LOCAL_GAME_DIR, os.environ['DIR_STEAM_MOD_DOWNLOAD'], GAME_WORKSHOP_ID)

    
    print(STEAMCMD_DIR)
    print(LOCAL_GAME_ID)
    print(LOCAL_GAME_DIR)
    print(LOCAL_MOD_DIR)
    print(LOCAL_KEYS_DIR)
    print(STEAM_DOWNLOAD_DIR)
    print(STEAM_USERNAME)
    print(STEAM_PASSWORD)
    print(GAME_SERVER_ID)
    print(GAME_WORKSHOP_ID)

    gc_client = GCC.GameConfigClient(LOCAL_GAME_ID) ## NEEDS PROPER TESTING
    steam_client = SCC.SteamCMDClient(
        LOCAL_GAME_DIR,
        STEAM_DOWNLOAD_DIR,
        STEAM_USERNAME,
        STEAM_PASSWORD
    )
    
    steam_client.install_game(GAME_SERVER_ID)

    gc_client.handle_mod_configuration(
        steam_client,
        GAME_SERVER_ID,
        LOCAL_GAME_DIR,
        LOCAL_MOD_DIR,
        STEAM_DOWNLOAD_DIR
    )

if __name__ == '__main__':
    main()
