[project]
name = "cloud_server_tool"
version = "0.1.0"
description = ""
authors = [
    {name = "Adam Connolly",email = "45522351+aconn1994@users.noreply.github.com"}
]
requires-python = ">=3.13"
dependencies = [
    "pylint (>=3.3.4,<4.0.0)",
    "ruff (>=0.9.4,<0.10.0)",
    "pytest (>=8.3.4,<9.0.0)",
    "coverage (>=0.7.8)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cloud_server_tool"
version = "0.0.0"
description = ""
authors = ["Adam Connolly aconn1994@gmail.com"]
packages = [{include = "docker"},{include = "game"}]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.dependencies]
python = ">=3.13"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pylint = ">=3.3.4,<4.0.0"
ruff = ">=0.9.4,<0.10.0"
pytest = ">=8.3.4,<9.0.0"
coverage = ">=7.8.0"
