name: Development Image Build

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: Path to dockerfile
        type: string
        default: "local_env/images/base_image/Dockerfile"
      docker_build_dir:
        description: Docker build directory (default = '.')
        default: "."
        type: string
      gcr_repo_path:
        description: GCR path
        type: string
        default: cst_development_images
      image_tag:
        description: Tag to apply to images
        type: string
        default: cst_base

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build, tag and push image to Amazon ECR
        id: build-publish
        shell: bash
        run: |
          docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.dockerfile_path }}" -t "${{ inputs.gcr_repo_path }}:${{ inputs.image_tag }}"
          docker push "ghcr.io/aconn1994/${{ inputs.gcr_repo_path }}:${{ inputs.image_tag }}"
          echo "Image ${{ inputs.image_tag }} is pushed to ghcr.io/aconn1994/${{ inputs.gcr_repo_path }}"
          echo "image_tag=${{ inputs.image_tag }}" 
          echo "full_image=ghcr.io/aconn1994/${{ inputs.gcr_repo_path }}:${{ inputs.image_tag }}"
