name: Linting (Python, Terraform)

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aconn1994/cst_base:main
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Format
        working-directory: ./terraform/aws
        run: terraform fmt -check -recursive
        continue-on-error: true
      - name: Python Linting/Formatting Check CICD package
        working-directory: .
        run: /bin/bash .cicd/bash/linters/python-format.sh .cicd/python .cicd/python cicd "check_arg" .cicd/python/pyproject.toml /usr/local/bin/python3
        continue-on-error: true
      - name: Python Linting/Formatting Check cst package
        working-directory: .
        run: /bin/bash .cicd/bash/linters/python-format.sh lib/python/cst lib/python/cst cst "check_arg" lib/python/cst/pyproject.toml /root/venvs/cst/bin/python3
