name: Testing (Python, Terraform)

on:
  workflow_call:
  workflow_dispatch:
  push:

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-tester:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/aws
    steps:
      - uses: actions/checkout@v4
      - name: Step Terraform with specific version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.11.4'
      - name: Initialize Terraform...
        run: terraform init
        continue-on-error: true
      - name: Validating Terraform
        run: terraform validate -no-color
        continue-on-error: true
  python-tester:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aconn1994/cst_base:main
    steps:
      - uses: actions/checkout@v4
#      - name: Python Testing CICD package
#        working-directory: .
#        run: /bin/bash .cicd/bash/testers/coverage-pytest.sh .cicd/python .cicd/python cst_cicd pyproject.toml python3
#        continue-on-error: true
      - name: Python Testing cloud-server-tool package
        working-directory: .
        run: /bin/bash .cicd/bash/testers/coverage-pytest.sh lib/python/cloud-server-tool lib/python/cloud-server-tool cloud-server-tool pyproject.toml /root/venvs/cloud-server-tool/bin/python3
